### PR TITLE
chore: release-please machinery

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by johanneskoester** [comment]
@mbhall88 @bricoletc sorry for maybe merging this too fast. Would release please be ok for you, otherwise I can also revert this. In any case, it would mean that we give up the dev branch and PRs get merged into master (at least that would be the simple solution).

**Comment by mbhall88** [comment]
What is release-please? And what is it's benefit over our existing release process?

**Comment by johanneskoester** [comment]
Release-please is an action that automatically generates a release plus changelog from the commit log: https://github.com/google-github-actions/release-please-action

One simply has to use conventional commit messages (feat:, fix:, etc.). From that, release please automatically generates a release PR, and when you merge that you get the new release. Very handy because generating a new release is just a matter of seconds then. It saves me a lot of time in maintaining snakemake, rust-bio, etc.

**Comment by johanneskoester** [comment]
this pr adds release please and an action for checking that commits generated from PRs have conventional commit messages such that release please can properly parse them.

**Comment by mbhall88** [comment]
Ok. Would you be able to link to some docs that outline the expected commit messages etc. in the contributing document?

**Pull request merged**
