### PR TITLE
Fix #91

### LINKED ISSUE #91: Error with else and if statement
Hi!

Snakefmt failes while parsing my workflow:

```
 if config["programs"]["Duplicates"] == "fgbio":
    include: "../rules/Alignment/fgbio.smk"
else:
    if config["programs"]["markduplicate"] == "GPU":
        include: "../rules/Alignment/GPU_alignment.smk"
    else:
        include: "../rules/Alignment/bwa-mem.smk"
        include: "../rules/Alignment/MarkDuplicates.smk"
```

with the following message

> [ERROR] In file "src/Snakemake/workflow/Twist_DNA_workflow.smk":  'InvalidPython: Got error:
> ```
> Cannot parse: 1:2: if:
> ```
> while formatting code with black.'
> [INFO] In file "src/Snakemake/workflow/Twist_DNA_workflow.smk":  1 file(s) raised parsing errors

running black manually gives me no errors. 

if I remove the if statement after else I get no errors.

```
if config["programs"]["Duplicates"] == "fgbio":
    include: "../rules/Alignment/fgbio.smk"
else:
    include: "../rules/Alignment/GPU_alignment.smk"
```

### PR DESCRIPTION
**Pull request by bricoletc**
#91 spotted a problem with nested if/else conditionals for including config files. This showed the regexp
we had for spotting these conditionals was incomplete, which I fixed, with added unit test.

This part of the code, where python syntax is 'glued' with snakemake syntax, is tricky to get right- I anticipate more edge cases exist, but I think we should wait to see them in real files rather than try and anticipate them all.

### CODE REVIEW

**Comment by bricoletc** [comment]
Update; #93 raises concerned related to this, which should be addressed in this PR too, will update it as explore fixes.

**Review by mbhall88 — APPROVED** [review]
Awesome work @bricoletc!

I agree, there are likely all sorts of weird edge cases, but worry about them when/if they arise.

**Comment by Smeds** [comment]
The latest commit gives me some strange results. Example

```
if config["programs"]["Trimming"] == "Cutadapt":

    include: "../rules/Fastq/Cutadapt_trimming.smk"


elif config["programs"]["Trimming"] == "Fastp":

    include: "../rules/Fastq/Fastp_trimming.smk"


else:

    include: "../rules/Fastq/move_fastq.smk"


# include: "../rules/CNV/ONCOCNV.smk"
# include: "../rules/CNV/cnvkit.smk"
# include: "../rules/QC/check_coverage.smk"
# include: "../rules/VCF_fix/Collect_results_DNA.smk" #Change folder!
# include: "../rules/Mutect2/Mutect2.smk"


if config["programs"]["Duplicates"] == "fgbio":

    include: "../rules/Alignment/fgbio.smk"


else:
    if config["programs"]["markduplicate"] == "GPU":

        include: "../rules/Alignment/GPU_alignment.smk"


    else:

        include: "../rules/Alignment/bwa-mem.smk"
        include: "../rules/Alignment/MarkDuplicates.smk"
```


Snakefmt wants to make the following modifications

```
  if config["programs"]["Trimming"] == "Cutadapt":
  
      include: "../rules/Fastq/Cutadapt_trimming.smk"
  
  
  elif config["programs"]["Trimming"] == "Fastp":
  
      include: "../rules/Fastq/Fastp_trimming.smk"
  
  
  else:
  
      include: "../rules/Fastq/move_fastq.smk"
  
  
- # include: "../rules/CNV/ONCOCNV.smk"
+     # include: "../rules/CNV/ONCOCNV.smk"
? ++++
- # include: "../rules/CNV/cnvkit.smk"
+     # include: "../rules/CNV/cnvkit.smk"
? ++++
- # include: "../rules/QC/check_coverage.smk"
+     # include: "../rules/QC/check_coverage.smk"
? ++++
- # include: "../rules/VCF_fix/Collect_results_DNA.smk" #Change folder!
+     # include: "../rules/VCF_fix/Collect_results_DNA.smk" #Change folder!
? ++++
- # include: "../rules/Mutect2/Mutect2.smk"
+     # include: "../rules/Mutect2/Mutect2.smk"
? ++++
  
  
- if config["programs"]["Duplicates"] == "fgbio":
+     if config["programs"]["Duplicates"] == "fgbio":
? ++++
  
      include: "../rules/Alignment/fgbio.smk"
  
  
  else:
      if config["programs"]["markduplicate"] == "GPU":
  
          include: "../rules/Alignment/GPU_alignment.smk"
  
  
      else:
  
          include: "../rules/Alignment/bwa-mem.smk"
          include: "../rules/Alignment/MarkDuplicates.smk"
```

**Comment by bricoletc** [comment]
@Smeds  here's commit https://github.com/snakemake/snakefmt/pull/92/commits/01c1f872f69ea9bbcf8431471cb195c31d6a6e54 to fix that.

**Comment by Smeds** [comment]
Nice=)

**Pull request merged**
