### PR TITLE
Fix three parsing bugs and bump version

### PR DESCRIPTION
**Pull request by bricoletc**
(From changelog)

### Fixed

* Three parsing-related bugs:
  - Complex lambda function syntax ([#108][108])
  - Argument unpacking ([#109][109])
  - Multiline parameters ([#111][111])

### CODE REVIEW

**Comment by bricoletc** [comment]
The key things I did are:

i) Refactor parameter-parsing code into `syntax.py`
ii) Common token parsing to all codebase now, leading to consistent spacing between tokens 
iii) wrap certain calls to black in a fake function when the black-formatted string is 'function-like' (eg stuff inside `input:`

With unit tests for the 3 fixed bugs

**Review by mbhall88 — APPROVED** [review]
Nice work Brice. Sorry, I've been quiet - writing up at the moment.

One thing I just realised that might also be useful for #112 - we might want to change the version specifier for black to use `>=` rather than `^`. Long story short the `^` form means we aren't actually getting the latest version. Up to you whether you want to do this in this PR or not

**Comment by bricoletc** [comment]
Cheers- about #112, can you remind me how the conda package is built, I can't seem to find an indication in the action yaml files under `.github` or a conda recipe in the repo

**Comment by mbhall88** [comment]
> Cheers- about #112, can you remind me how the conda package is built, I can't seem to find an indication in the action yaml files under `.github` or a conda recipe in the repo

The recipe is [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/snakefmt/meta.yaml). The autobump is triggered when bioconda detect a new release on our github repo.

[This line](https://github.com/bioconda/bioconda-recipes/blob/6940614ebcf4761f7c3a75e1a49c0c972f07de15/recipes/snakefmt/meta.yaml#L27) shows the version pinning problem for black I mentioned above

**Pull request merged**
