### PR TITLE
Allow check and diff together

### LINKED ISSUE #68: Use return code of `snakefmt --diff` to signal whether modifications are made
`snakefmt --check` uses its return code to signal whether the source file needs changes. `snakefmt --diff` shows which changes are needed but does not signal its status using its return code. Using both parameters at the same time is not possible (`[WARNING] Both --check and --diff/--compact-diff given. Only running --check...`).

It would be great if `--diff` and `--compact-diff` would also set the return code to `0` if no changes are made and `1` instead. This would be useful e.g. in https://github.com/github/super-linter/pull/713.

### PR DESCRIPTION
**Pull request by mbhall88**
This PR closes #68 

### Changed

- allow `--check` and `--diff` to be used together [#68]

### CODE REVIEW

**Comment by mbhall88** [comment]
Note: The coverage has reduced as I've removed lines from `snakefmt`. Annoying that codecov can't figure out that that doesn't technically mean coverage has decreased, especially considering the diff coverage is 100%.

**Review by bricoletc — APPROVED** [review]
Looks great, I find it makes reading and understanding the code smoother, which is a sign this is a better design too

**Comment by bricoletc** [comment]
@mbhall88 happy to merge this in and then could you try this branch on your workflows especially to check #67 .
If happy we can then PR to master and make new release, I will need to add to CHANGELOG though

**Comment by mbhall88** [comment]
> @mbhall88 happy to merge this in and then could you try this branch on your workflows especially to check #67 .
> If happy we can then PR to master and make new release, I will need to add to CHANGELOG though

Sure. Feel free to push your changelog additions directly to `dev` once this PR is merged :+1: then I'll pull `dev` locally tomorrow and start testing it

**Pull request merged**
