### PR TITLE
feat: add support for new exclude expressions in use rule statements

### PR DESCRIPTION
**Pull request by johanneskoester**
Introduced by https://github.com/snakemake/snakemake/pull/1717

### CODE REVIEW

**Review by mbhall88 — APPROVED** [review]
@johanneskoester could you format that file with black before merging this?

**Comment by johanneskoester** [comment]
Mhm, I did. Let me check.

**Comment by johanneskoester** [comment]
Oh no, I did it via the github interface, sorry.

**Comment by johanneskoester** [comment]
Mhm, I guess I somehow have destroyed the parsing for use rule statements...

**Comment by johanneskoester** [comment]
If the issue is obvious for you, could you help? If not, I will try to debug it later.

**Comment by mbhall88** [comment]
It's not immediately obvious to me sorry. I won't be able to look at this until sometime late next week either sorry.

**Pull request merged**
