### PR TITLE
Support new snakemake keywords `prefix` and `default_target`

### LINKED ISSUE #130: prefix keyword in module declaration not recognised
Hi,

Thanks for the great package! Snakemake 6.13 introduced the `prefix` keyword in module declaration blocks, which can look like this:
````snakemake
module:
    snakefile: "other/Snakefile"
    prefix: "other"
````
This is not yet recognised by snakefmt; the above module declaration is rejected as invalid.

### PR DESCRIPTION
**Pull request by koen-vg**
Hi! Thanks for the great project; snakefmt is much appreciated.

Recently two new keywords have been added to snakemake: `prefix` (in module blocks) and `default_target` (in rules). This pull request adds support to snakefmt for both. I have also included both in test. All tests pass, and I have also tested this with success on a more involved snakefile I personally work with.

This also closes #130.

Let me know if any improvements are changes are needed or wished for before merging.

### CODE REVIEW

**Comment by bricoletc** [comment]
Hi @koen-vg , thanks for your contribution :) This looks good! By default we merge into dev and then push new versions to master.

I'm just a bit surprised that all tests passed for you, as our current snakemake dependency version fails 'grammar completeness' tests. So I recommend we merge this in dev and I then push an update of snakemake dep. version to latest. I checked all tests/lints pass from there.

@mbhall88 happy to merge?

**Review by bricoletc — APPROVED** [review]

**Comment by bricoletc** [comment]
@mbhall88 after your review we either wait for @koen-vg to push that snakemake update commit here, or we merge to dev and do it ourselves

**Comment by koen-vg** [comment]
Right, I did have to update to the latest version of snakemake, 6.15, but seem to have forgotten to document that. I'll try to push the snakemake update, that would be to the poetry.lock file?

**Comment by koen-vg** [comment]
Alright I have to admit I'm not super familiar with poetry; the latest commit is what I got after updating the snakemake version in pyproject.toml and then running `poetry update`; hopefully that was the intention.

**Comment by mbhall88** [comment]
All looks good. @koen-vg could you please add your changes to the CHANGELOG as well?

**Comment by bricoletc** [comment]
Thanks @koen-vg ! so I've just done two things:
* Fixed CHANGELOG conflict in this PR on dev branch
* Modified your poetry update commit, because you ran `poetry update` but I would rather we do `poetry update snakemake` only here (after, as you did, modifying the pyproject.toml snakemake version). I know poetry is not so easy at first (https://python-poetry.org/docs/basic-usage/#specifying-dependencies).  For me, no need to update all dependencies, if they ain't broke, let's not change them :-) @mbhall88 thoughts?

@koen-vg  I've pushed your changes plus those two points above to `dev`. You are still author of the fixing and changelog commits. @mbhall88 i would suggest we close this pull request since I've merged the material into dev, if you agree.

**Comment by koen-vg** [comment]
That all sounds very good. Thanks for making it easy to contribute to this project!

**Comment by mbhall88** [comment]
>  For me, no need to update all dependencies, if they ain't broke, let's not change them :-) @mbhall88 thoughts?

Fine by me. This does remind me though, black is now stable so we will need to update that dependency soon. But agree with just updating snakemake here

> @koen-vg I've pushed your changes plus those two points above to dev. You are still author of the fixing and changelog commits. @mbhall88 i would suggest we close this pull request since I've merged the material into dev, if you agree.

Ok. Normally I would prefer you push to this PR and we solve conflicts here, but it's done now. So yes, closing this makes sense.

**Comment by bricoletc** [comment]
For future ref- not sure how I could have pushed a change that removed one of the commits (updating all dependencies), i.e. rewriting history, to the `from` branch?

**Comment by mbhall88** [comment]
Ah didn't realise you had removed a commit. Ignore me.

**Pull request closed without merging**
